{
    'name': 'Student Management',
    'version': '1.0',
    'summary': 'Manage student records',
    'description': 'Custom module for managing students in Odoo',
    'author': 'Ansh Soni',
    'category': 'Education',
    'depends': ['base', 'account', 'sale', 'website', 'mail', 'website_sale'],
    'data': [
        'security/student_security.xml',
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        'data/student_cron.xml',
        'views/student_views.xml',
        'views/student_standard_views.xml',
        'views/student_subject_views.xml',
        'views/student_result_views.xml',
        'views/student_status_wizard_views.xml', 
        'views/student_fees_views.xml',
        'views/sale_order_views.xml',
        'views/sale_order_package_views.xml',
        'views/student_fees_wizard_views.xml',
        'views/student_portal_templates.xml',
        'views/student_registration_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'student_management/static/src/product_catalog/duplicate_product_dialog.js',
            'student_management/static/src/product_catalog/duplicate_product_dialog.xml',
            'student_management/static/src/product_catalog/kanban_controller.js',
        ],
    },
    'installable': True,
    'application': True,
}