{
    'name': 'Student Management',
    'version': '1.0',
    'summary': 'Manage student records',
    'description': 'Custom module for managing students in Odoo',
    'author': 'Ansh Soni',
    'category': 'Education',
    'depends': ['base', 'account', 'sale', 'website', 'mail', 'website_sale'],
    'data': [
        'security/student_security.xml',
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        'views/student_views.xml',
        'views/student_standard_views.xml',
        'views/student_subject_views.xml',
        'views/student_result_views.xml',
        'views/student_status_wizard_views.xml', 
        'views/student_fees_views.xml',
        'views/student_fees_wizard_views.xml',
        'views/student_portal_templates.xml',
        'views/student_registration_templates.xml',
    ],
    'installable': True,
    'application': True,
}