from odoo.tests.common import TransactionCase
from odoo.exceptions import ValidationError
from odoo import fields

class TestStudentFees(TransactionCase):

    def setUp(self):
        super(TestStudentFees, self).setUp()
        
        # Setup standard and student
        self.standard = self.env['student.standard'].create({
            'standard': '12',
            'division': 'A',
            'fees_amount': 6000.0,
        })
        self.student = self.env['student.management'].create({
            'name': 'Bob Smith',
            'roll_number': 'S120',
            'age': 17,
            'email': 'bob.smith@example.com',
            'standard_id': self.standard.id,
        })
        # Remove automatically created fees if any (since setUp does auto fee creation)
        self.student.fee_ids.unlink()

    def test_01_fees_constraints(self):
        """Test validation on fee amount."""
        with self.assertRaises(ValidationError):
            self.env['student.fees'].create({
                'student_id': self.student.id,
                'description': 'Test negative fees',
                'amount': -100.0,
            })
        with self.assertRaises(ValidationError):
            self.env['student.fees'].create({
                'student_id': self.student.id,
                'description': 'Test zero fees',
                'amount': 0.0,
            })

    def test_02_fee_action_pay(self):
        """Test action_pay creates a sales order and updates fee state accordingly."""
        fee = self.env['student.fees'].create({
            'student_id': self.student.id,
            'description': 'Term 1 Fees',
            'amount': 3000.0,
        })

        # Pre-checks
        self.assertEqual(fee.state, 'draft')
        self.assertFalse(fee.sale_order_id)

        # Pay fee
        fee.action_pay()

        # Check sales order creation
        self.assertTrue(fee.sale_order_id, "Sales Order should be generated.")
        self.assertEqual(fee.sale_order_id.partner_id.id, self.student.partner_id.id)
        self.assertEqual(len(fee.sale_order_id.order_line), 1)
        self.assertEqual(fee.sale_order_id.order_line[0].price_unit, 3000.0)
        self.assertEqual(fee.sale_order_id.order_line[0].name, 'Term 1 Fees')
        
        # Confirm sales order to test state computation
        fee.sale_order_id.action_confirm()
        self.assertEqual(fee.state, 'paid', "Fee state should transition to paid after Sales Order confirmation.")
        # Re-compute status of student
        self.student._compute_fee_status()
        self.assertEqual(self.student.fee_status, 'paid', "Student fee status should transition to paid.")

    def test_03_fees_wizard(self):
        """Test the student fees wizard workflow."""
        # Open fees wizard with default values
        wizard_context = {
            'default_student_id': self.student.id,
        }
        
        # Check default amount
        default_vals = self.env['student.fees.wizard'].with_context(wizard_context).default_get(['amount'])
        self.assertEqual(default_vals.get('amount'), 6000.0, "Default amount in wizard should match standard fees.")

        # Create wizard record
        wizard = self.env['student.fees.wizard'].with_context(wizard_context).create({
            'student_id': self.student.id,
            'description': 'Wizard Paid Fees',
            'amount': 5500.0,
        })

        self.assertEqual(wizard.state, 'draft')

        # Trigger wizard payment action
        wizard.action_pay_fees()

        # Check wizard updates state to paid
        self.assertEqual(wizard.state, 'paid')

        # Check corresponding student.fees record
        fee = self.env['student.fees'].search([('student_id', '=', self.student.id)])
        self.assertEqual(len(fee), 1)
        self.assertEqual(fee.amount, 5500.0)
        self.assertEqual(fee.description, 'Wizard Paid Fees')
        self.assertTrue(fee.sale_order_id)
        self.assertTrue(fee.invoice_id, "Invoice should be automatically generated by wizard.")
        self.assertEqual(fee.invoice_id.state, 'posted', "Invoice should be posted.")
        
        # Check chatter log on student
        messages = self.env['mail.message'].search([
            ('model', '=', 'student.management'),
            ('res_id', '=', self.student.id),
        ])
        body_texts = [m.body for m in messages]
        has_message = any("Wizard Paid Fees" in body and "5500" in body for body in body_texts)
        self.assertTrue(has_message, "A chatter message should be logged for paid fees.")

    def test_04_multi_company_fee_payment(self):
        """Test that action_pay creates a sales order in the student's company, not current user's company."""
        company_b = self.env['res.company'].create({'name': 'Delhi Campus'})
        
        # Create standard and student in Delhi Campus
        standard_delhi = self.env['student.standard'].create({
            'standard': '12',
            'division': 'B',
            'fees_amount': 7000.0,
            'company_id': company_b.id,
        })
        student_delhi = self.env['student.management'].create({
            'name': 'Delhi Bob',
            'roll_number': 'S121',
            'age': 17,
            'email': 'delhi.bob@example.com',
            'standard_id': standard_delhi.id,
            'company_id': company_b.id,
        })
        # Remove automatically created fees if any
        student_delhi.fee_ids.unlink()

        # Create a new fee for this student
        fee = self.env['student.fees'].create({
            'student_id': student_delhi.id,
            'description': 'Delhi Term 1 Fees',
            'amount': 3500.0,
        })

        # Check company_id of the fee is computed correctly (related)
        self.assertEqual(fee.company_id.id, company_b.id, "Fee record should inherit company_id from student.")

        # Call action_pay
        fee.action_pay()

        # Check that the sales order belongs to Company B (Delhi Campus)
        self.assertTrue(fee.sale_order_id, "Sales Order should be generated.")
        self.assertEqual(fee.sale_order_id.company_id.id, company_b.id, "Sales Order should belong to student's company.")


from odoo.tests.common import HttpCase
from unittest.mock import patch, Mock
import re

class TestStudentFeesPortal(HttpCase):

    def setUp(self):
        super(TestStudentFeesPortal, self).setUp()
        
        # Set up System Parameters
        self.env['ir.config_parameter'].sudo().set_param('student_management.razorpay_key_id', 'rzp_test_dummykey')
        self.env['ir.config_parameter'].sudo().set_param('student_management.razorpay_key_secret', 'dummysecret')

        # Setup standard and student
        self.standard = self.env['student.standard'].create({
            'standard': '12',
            'division': 'A',
            'fees_amount': 6000.0,
        })
        self.student = self.env['student.management'].create({
            'name': 'Portal Student',
            'roll_number': 'S199',
            'age': 18,
            'email': 'portal.student@example.com',
            'standard_id': self.standard.id,
        })
        # Remove automatically created fees if any
        self.student.fee_ids.unlink()

        # Create the fee record
        self.fee = self.env['student.fees'].create({
            'student_id': self.student.id,
            'description': 'Term 1 Fees',
            'amount': 3000.0,
        })

        # Create student user linked to partner
        self.student_user = self.env['res.users'].create({
            'name': 'Portal Student User',
            'login': 'portal.student@example.com',
            'email': 'portal.student@example.com',
            'partner_id': self.student.partner_id.id,
            'password': 'password123',
            'group_ids': [(6, 0, [self.env.ref('student_management.group_student').id])]
        })
        
        # Start patching requests.post
        self.patcher = patch('requests.post')
        self.mock_post = self.patcher.start()

    def tearDown(self):
        self.patcher.stop()
        super(TestStudentFeesPortal, self).tearDown()

    def test_portal_pay_fee_page(self):
        """Test payment page initiation and Razorpay order generation."""
        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            'id': 'order_dummy123',
            'amount': 300000,
            'currency': 'INR',
        }
        self.mock_post.return_value = mock_response

        # Authenticate as student
        self.authenticate('portal.student@example.com', 'password123')

        # Request payment page
        response = self.url_open(f'/my/student/fees/pay/{self.fee.id}')
        
        self.assertEqual(response.status_code, 200, "Payment page should load successfully.")
        self.assertIn(b'Connecting to Razorpay', response.content)
        self.assertIn(b'order_dummy123', response.content)
        self.assertIn(b'rzp_test_dummykey', response.content)

    def test_portal_pay_fee_callback_success(self):
        """Test successful payment callback with valid Razorpay signature."""
        self.authenticate('portal.student@example.com', 'password123')
        
        # Create Sales Order
        self.fee.action_pay()
        self.assertTrue(self.fee.sale_order_id)
        self.assertEqual(self.fee.sale_order_id.state, 'draft')

        # Generate correct signature for dummy values
        import hmac
        import hashlib
        msg = b"order_dummy123|pay_dummy123"
        secret = b"dummysecret"
        signature = hmac.new(secret, msg, hashlib.sha256).hexdigest()

        # Open fees list page to get CSRF token
        res = self.url_open('/my/student/fees')
        csrf_match = re.search(r'csrf_token:\s*"([^"]+)"', res.text)
        if not csrf_match:
            csrf_match = re.search(r'name="csrf_token"\s+value="([^"]+)"', res.text)
        csrf_token = csrf_match.group(1) if csrf_match else ''

        # Submit callback POST
        payload = {
            'csrf_token': csrf_token,
            'razorpay_payment_id': 'pay_dummy123',
            'razorpay_order_id': 'order_dummy123',
            'razorpay_signature': signature,
        }
        res_post = self.url_open(
            f'/my/student/fees/pay/callback/{self.fee.id}',
            data=payload
        )
        
        # Verify success redirect
        self.assertEqual(res_post.status_code, 200)
        self.assertIn('payment_success=1', res_post.url)
        
        # Verify state transitioned to paid, sale order confirmed, and invoice created
        self.fee.invalidate_recordset()
        self.assertEqual(self.fee.state, 'paid', "Fee record should be marked as paid.")
        self.assertEqual(self.fee.sale_order_id.state, 'sale', "Associated Sale Order should be confirmed.")
        self.assertTrue(self.fee.invoice_id, "Invoice should be automatically generated.")
        self.assertEqual(self.fee.invoice_id.state, 'posted', "Invoice should be posted.")

    def test_portal_pay_fee_callback_invalid_signature(self):
        """Test payment callback with an invalid Razorpay signature."""
        self.authenticate('portal.student@example.com', 'password123')
        
        self.fee.action_pay()
        self.assertTrue(self.fee.sale_order_id)
        self.assertEqual(self.fee.sale_order_id.state, 'draft')

        # Open fees list page to get CSRF token
        res = self.url_open('/my/student/fees')
        csrf_match = re.search(r'csrf_token:\s*"([^"]+)"', res.text)
        if not csrf_match:
            csrf_match = re.search(r'name="csrf_token"\s+value="([^"]+)"', res.text)
        csrf_token = csrf_match.group(1) if csrf_match else ''

        # Submit callback POST with bad signature
        payload = {
            'csrf_token': csrf_token,
            'razorpay_payment_id': 'pay_dummy123',
            'razorpay_order_id': 'order_dummy123',
            'razorpay_signature': 'invalid_signature_hash',
        }
        res_post = self.url_open(
            f'/my/student/fees/pay/callback/{self.fee.id}',
            data=payload
        )
        
        # Verify error redirect
        self.assertEqual(res_post.status_code, 200)
        self.assertIn('payment_error=invalid_signature', res_post.url)
        
        # Verify state did not change
        self.fee.invalidate_recordset()
        self.assertEqual(self.fee.state, 'draft')
        self.assertEqual(self.fee.sale_order_id.state, 'draft')

    def test_portal_pay_fee_access_control(self):
        """Test that non-student users are blocked from access."""
        # Create portal user not associated with any student
        self.non_student_user = self.env['res.users'].create({
            'name': 'Other User',
            'login': 'other.user@example.com',
            'email': 'other.user@example.com',
            'password': 'password123',
            'group_ids': [(6, 0, [self.env.ref('base.group_portal').id])]
        })

        self.authenticate('other.user@example.com', 'password123')

        # Request payment page
        response = self.url_open(f'/my/student/fees/pay/{self.fee.id}')
        
        # Verify redirect to non-student portal dashboard /my
        self.assertIn('/my', response.url)
        self.assertNotIn('fees/pay', response.url)


